config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'words#index'
  resources :words, only:[:index, :show]
  resources :users, only:[:show]
    
  resources :wordcreaters, only:[:new, :create]
  # get 'words' => 'words#index'
  # get 'words/new' -> 'words#new'

  # get 'users/:id' => 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :word
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    {id: 1, name:'happy'}, {id: 2, name:'impression'}, {id: 3, name: 'cheer up'},
    {id: 4, name:'other'}
]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :words
  has_many :wordcreaters
end

app/models/word.rb
class Word < ApplicationRecord
extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user, optional: true
  belongs_to :wordcreater, optional: true
  belongs_to_active_hash :genre
  has_many :comments
  mount_uploader :image, ImageUploader

  validates :genre_id, presence: true

end

app/models/wordcreater.rb
class Wordcreater < ApplicationRecord
  has_many :words
  belongs_to :users
  accepts_nested_attributes_for :words
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    "/"
  end

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @username = current_user.name
    @words = Word.where(user_id: current_user.id)
  end
end

app/controllers/wordcreaters_controller.rb
class WordcreatersController < ApplicationController
  before_action :move_to_index, except: :index

  def index
    @wordcreaters = Wordcreaters.all
  end

  def new
    @wordcreater = Wordcreater.new
    @wordcreater.words.build
  end


  def create
    @wordcreater = Wordcreater.new(wordcreater_params)
    @wordcreater.save
    redirect_to root_path
  end


  private
    def wordcreater_params
      params.require(:wordcreater).permit(:id, :name, words_attributes:[:id, :word, :image, :genre_id]).merge(user_id: current_user.id)
    end


    def move_to_index
    redirect_to controller: :words,action: :index  unless user_signed_in?
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def index
    @words = Word.all
    @random = Word.order("Rand()").limit(2)
  end

  def new
    @word = Word.new
    
  end

  def show
    @word = Word.find(params[:id])
    @wordcreater = Wordcreater.find_by(id: @word.wordcreater.id)
    @user = User.find_by(id:@wordcreater.user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wordcreaters_helper.rb
module WordcreatersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/_notifications.html.haml
.notification
  -flash.each do |key, value|
    =content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FavoriteWordsNote
    = csrf_meta_tags
    = csp_meta_tag
    %link{href: "https://fonts.googleapis.com/css?family=Fredoka+One&display=swap", rel:"stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/shared/_header.html.haml
%header
  .main
    .main__upside
      .main__upside__name
      =link_to "/" do
        favorite words note
      .main__upside__search
        -# = form_tag path, method: :get, class:"main__upside__search__form" do
        -#   = text_field_tag :keyword, params[:keyword], class: "main__upside__search__form--folder", placeholder:"探したい人を入力してください"
        -#   = button_tag class:'main__upside__search--button'
        -#     = fa_icon 'search', class: 'main__upside__search--icon'
    .main__downside
      .main__downside__button
        .main__downside__button__content
        - if user_signed_in?
          .main__downside__button__content__logout
          =link_to destroy_user_session_path, method: :delete, class:'button' do
            .main__downside__button__content__logout-name
              log out
        - else
          .main__downside__button__content__in
            .main__downside__button__content__in__login
            =link_to new_user_session_path,method: :get, class:'button' do
              log in
            .main__downside__button__content__in__signin
              =link_to new_user_registration_path, class:'button' do
                sign in
          
        .main__downside__user
        -if user_signed_in?
          =link_to "users/#{current_user.id}" do
            =fa_icon 'user', class: 'icon'

app/views/shared/_pencil.html.haml
.pencil
  = link_to new_wordcreater_path, class: 'link' do
    .pencil__main
      .pencil__main__text
        write
      .pencil__main__mark
        = fa_icon 'edit', class: 'icon'
  -# -else
  -#   = link_to root, class: 'link' do
  -#     .pencil__main
  -#       .pencil__main__text
  -#         出品
  -#       .pencil__main__mark
  -#         = fa_icon 'pencil-alt', class: 'icon'

app/views/shared/_userheader.html.haml
%header
  .main
    .main__upside
      .main__upside__name
      =link_to "/" do
        favorite words note
      .main__upside__search
        -# = form_tag path, method: :get, class:"main__upside__search__form" do
        -#   = text_field_tag :keyword, params[:keyword], class: "main__upside__search__form--folder", placeholder:"探したい人を入力してください"
        -#   = button_tag class:'main__upside__search--button'
        -#     = fa_icon 'search', class: 'main__upside__search--icon'
    .main__downside
      .main__downside__button
        .main__downside__button__content
        - if user_signed_in?
          .main__downside__button__content__logout
          =link_to destroy_user_session_path, method: :delete, class:'button' do
            .main__downside__button__content__logout-name
              log out
            -# .main__downside__button__content__post
            -# = link_to "投稿する",new_wordcreater_path, method: :get, class:'button' do
        -# - else
        -#   .main__downside__button__content__login
        -#   =link_to new_user_session_path,method: :post, class:'button' do
        -#     log in
        -#   .main__downside__button__content__signin
        -#   =link_to "新規登録", class:'button' do
        -#     sinnkitouroku

        .main__downside__user
        =link_to "/" , class:'button' do
          back
          -# =fa_icon 'user', class: 'icon'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", '#', class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/show.html.haml
= render 'shared/userheader'
.mypage
  .mypage__title
    = @username + "'s page"
  .mypage__note
    - @words.each do |word|
      =link_to "/words/#{word.id}" do
        .mypage__note__box
          %p.mypage-note__box__word
            = word.word

app/views/wordcreaters/new.html.haml
= render 'shared/header'
.new
  .new__contents
  = form_for @wordcreater do |f|
    .new__contents__field
    .new__contens__field__input
    = f.fields_for :words do |t|
      .new__contents__field__input__word
        %h2.new__contents__field__input__word-title
          word
        .new__contents__field__input__word-box
          = t.text_area :word, placeholder:"好きな言葉を入力してください", cols:"20", rows:"4", class:"new__contents__field__input__word__box"
      .new__contents__field__input__person
        %h2.new__contents__field__input__person-title
          person   
        .new__contents__field__input__person-box
          =f.text_area :name, placeholder:"言葉を残した人の名前を入力してください", cols:"30", rows:"4", class:"new__contents__field__input__word__box"
      .new__contents__field__input__genre
        %h2.new__contents__field__input__genre-title
          genre (※Required)
        .new__contents__field__input__genre__box
          .new__contents__field__input__genre__box__top
            = t.collection_select :genre_id,Genre.all, :id,:name,{include_blank: '---'}, class:"collection_box"
      .new__contents__field__input__image
        .new__contents__field__input__image-title
          image
          .new__contents__field__input__image__box
            = t.label :image, class:"new__contents__field__input__image",for:"myImage" do
              = fa_icon "image"
              = t.file_field :image, class:'hidden',id:'myImage'
        .new__contents__field__input__image__box-pre  
          %img#preview
    .new__contents__field__back
      .new__contents__field__back__button
        =link_to "/", class:'new__contents__field__back__button' do
          back
    .new__contents__field__submit
      -# .new__contents__field__submit__button
        -# =link_to "#", class:'new__contents__field__submit__button' do
    = f.submit class:'new__contents__field__submit__button'

app/views/words/index.html.haml
= render 'shared/header'
%article
  .rand
    recommend
    -@random.each do |random|
      =link_to "/words/#{random.id}" do
        .rand__box
          %p.rand__box__word
            = random.word
          .rand__box__image
            = image_tag random.image.url, class:"picture" if random.image.present?
  .note
    - @words.each do |word|
      =link_to "/words/#{word.id}" do
        .note__box
          %p.note__box__word
            = word.word
          .note__box__image
            = image_tag word.image.url, class:"picture" if word.image.present?
  = render 'shared/pencil'

app/views/words/new.html.haml
.new
  .new__contents
  = form_for @word, method: :post do |f|
    .new__contents__field
      Let's input about favorite words
    .new__contens__field__input
      .new__contents__field__input__word
        %h2.new__contents__field__input__word-title
          word
        =f.text_area :word, cols:30, rows: 10, placeholder:"好きな言葉を入力してください", maxlength:100, type:"text", name:"word", class:"new__contents__field__input__word__box"

      .new__contents__field__input__person
        %h2.new__contents__field__input__person-title
          person
        =f.text_field :wordcreater,  placeholder:"言葉を残した人の名前を入力してください", maxlength:100, type:"text", name:"person", class:"new__contents__field__input__word__box"
      .new__contents__field__input__genre
        %h2.new__contents__field__input__genre-title
          genre
        .new__contents__field__input__genre__box
          %select.new__contents__field__input__genre__box__top
            %option{value: "initial"}---
            %option{value: "happy"}happy
            %option{value: "impression"}impression
            %option{value: "cheer up"}cheer up
            %option{value: "another"}another
      .new__contents__field__input__image
        .new__contents__field__input__image-title
          image
        .new__contents__field__input__image__box
        
          -# =f.label :image, class:"new__contents__field__input__image",for:"myImage" do
          -#   = fa_icon "image"
          -#   = f.file_field :image,class:'hidden',id:'myImage'
        .new__contents__field__input__image__box-pre  
          %img#preview
    .new__contents__field__back
      .new__contents__field__back__button
        =link_to "/", class:'new__contents__field__back__button' do
          back
    .new__contents__field__submit
      -# .new__contents__field__submit__button
        -# =link_to "#", class:'new__contents__field__submit__button' do
    = f.submit class:'new__contents__field__submit__button'

app/views/words/show.html.haml
= render 'shared/header'
.show
  .note
    %ul.note__box
      %li.note__box__title
        word
        .note__box__title__contents
          = @word.word
      %li.note__box__title
        person
        .note__box__title__contents
          = @wordcreater.name
      %li.note__box__title
        genre
        .note__box__title__contents
          =Genre.find(@word.genre.id).name
      %li.note__box__title
        image
        .note__box__title__image-box
          = image_tag @word.image.url, class:"picture" if @word.image.present?
      %li.note__box__title
        user name
        .note__box__title__contents
          = @user.name
    .note__button
      = link_to "/" do
        top page